### ISSUE TITLE
No root password set after installation

### ISSUE THREAD

**Issue by merlinschumacher** [AnarchyLinux/installer#930] opened 2019-11-22 17:40 UTC
## Basic info:

**Anarchy version**:  1.0.8

**Installation method (VM/Host)**: Host

**System specifications (Processor, GPU, RAM ...)**: AMD Ryzen 1700, Radeon RX590, 32 GB RAM

## What you expected would happen

I expected the system to set the requested root password for the root user. I also expected to be asked that password at the login.

## What actually happened

The password was requested, but not set. A root login without any password request was possible.

## Steps needed to reproduce the bug

1. Install Anarchy including setting a root password
2. Boot the installed system
3. login as root on a terminal without providing a password

## Extra info

I've installed the system twice (for other reasons) both times this happened.
Here is a video of me logging in the second fresh install:
https://www.youtube.com/watch?v=-M4bSjOnYMY&feature=youtu.be

## Bug report checklist

* [x] I've read the [Reporting Issues Wiki Page](https://github.com/AnarchyLinux/installer/wiki/Reporting-issues)
* [x] I've removed unnecessary sections of the bug submission template
* [x] I understand that if I don't do everything listed in the checkmarks above my issue won't be considered a priority and may get closed at any time without warning, because I didn't take the time to properly submit my bug report

**Comment by lastweakness** [comment] 2019-11-30 13:42
No such issue for me...

**Comment by deadhead420** [comment] 2020-01-10 01:51
I'm looking into this now but I have just installed a fresh system and all passwords set correctly. I'll test more in a vm

**Comment by erazemkokot** [comment] 2020-01-13 17:28
Closing since the issue cannot be reproduced. Please try the installation again, preferably on a newly downloaded and checked (using the checksum) iso.

**Closed by erazemkokot** 2020-01-13 17:28 UTC
Labels: bug
