### ISSUE TITLE
Download links unreachable & Contact Form on website broken

### ISSUE THREAD

**Issue by sdo992** [AnarchyLinux/installer#907] opened 2019-10-22 20:42 UTC
## Basic info: Website Contact Form error & Download links unreachable

Website - 

```
"Unable to submit form
Make sure you open this page through a web server, Formspree will not work in pages browsed as HTML files. Also make sure that you're posting to https://formspree.io/contact@erazem.eu.

For geeks: could not find the "Referer" header."
```

1.0.7 ISO and Torrent File Download error:

**Anarchy version**:

**Installation method (VM/Host)**:

**System specifications (Processor, GPU, RAM ...)**:

## Steps needed to reproduce the bug

1.
2.
3.
4.

## Extra info

```
Logs,
Terminal output
```

## Bug report checklist

* [ ] I've checked for any existing issues similar to mine and tried the solutions provided there
* [ ] I've checked online for any existing fixes to my issue and added the link above
* [ ] I've tried taking logs and submitting them above

**Comment by erazemkokot** [comment] 2019-10-22 21:39
Can't reproduce on Firefox, which browser are you using? And are you blocking javascript or similar stuff?

**Comment by erazemkokot** [comment] 2019-11-07 18:54
Closing since two weeks passed without reply and issue isn't reporoducible.

**Closed by erazemkokot** 2019-11-07 18:54 UTC
Labels: bug, need more info
